### ISSUE TITLE
`treesit-node-match-p` is not available in Gnu Emacs 29.1

### ISSUE THREAD

**Issue by dhanak** [nverno/jq-ts-mode#2]
Your code uses the function `treesit-node-match-p`, but it isn't avaiable in Gnu Emacs 29.1. I found that it was [added to the C source in Apr 2023](https://lists.gnu.org/r/emacs-diffs/2023-04/msg00330.html), but it is probably only available in later releases. Could you provide a 29.1 compatible workaround for this, please?

**Comment by nverno** [comment]
Thanks! I replaced those uses in #3 , lmk if anything else isn't working in 29.1

**Comment by dhanak** [comment]
Well, that was quick! Thanks a lot, I tested the change by manually applying it to my local copy, and it works like a charm!
